name: flutter_bom_example
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.3.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  feature1:
    path: ./packages/feature1
  feature2:
    path: ./packages/feature2
  feature3:
    path: ./packages/feature3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^5.2.2
flutter:
  uses-material-design: true
