name: feature3
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  # declare dependencies without versions
  freezed_annotation:
  http:
  lottie:
  path_provider:
  shared_preferences:
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  # declare dependencies without versions
  freezed:
flutter:
